eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8097/eureka

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reservation_db2
    username: db_user2
    password: db_password2
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl_auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect